export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_START = 'CREATE_POST_START';
export const CREATE_POST_STOP = 'CREATE_POST_STOP';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';

export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_START = 'DELETE_POST_START';
export const DELETE_POST_STOP = 'DELETE_POST_STOP';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';

export const FETCH_POSTS = 'FETCH_POSTS';
export const START_POSTS_FETCHING = 'START_POSTS_FETCHING';
export const STOP_POSTS_FETCHING = 'STOP_POSTS_FETCHING';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';


export const LIKE_POST = 'LIKE_POST';
export const LIKE_POST_START = 'LIKE_POST_START';
export const LIKE_POST_STOP= 'LIKE_POST_STOP';
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const LIKE_POST_FAIL = 'LIKE_POST_FAIL';
